### ISSUE TITLE
Offline Usage

### ISSUE THREAD

**Issue by ghost** [wyolum/TouchSelfie#10]
What I have found is that in the setting I wish to use it (a camp), there is not always reliable internet and so while the online upload feature is nice is it possible to disable it so that the system can work offline as the system basically goes back and forth between working perfectly to not working at all due to not great internet.

**Comment by laurentalacoque** [comment]
Hi :)

A bit late for the camp I think but you should try this:
In `photobooth_gui.py`

- comment line 197 `#send_button.pack(side=RIGHT)`
- comment line 307 `#etext.pack()`

This will remove the send email buttons and text entry

- comment line 192 `#                        googleUpload(custom.PROC_FILENAME)`
- untick the SIGN ME IN checkbox in the `customize` menu

This will avoid network access, thus avoiding the application freezes
