### ISSUE TITLE
Preview is not visible

### ISSUE THREAD

**Issue by Fanny42** [wyolum/TouchSelfie#14]
Hi!
I have several problems.
First, I cannot see the preview : I have the countdown, but no image. No problem to get the pictures.
Second, I would like to change the size of the image to use this app on a bigger screen.
Anyone to help me ? Thank you in advance guys !

**Comment by wyojustin** [comment]
Sounds like the camera is not working.  Do the images appear after the countdown?  Regarding the size, that sounds easy, but you have to hunt around in the config settings.

**Comment by Fanny42** [comment]
I don't have any problem with the camera since I get the pictures on Google
and by email. This is just the preview that doesn't work.

Le sam. 26 mai 2018 à 19:15, Justin Shaw <notifications@github.com> a
écrit :

**Comment by wyojustin** [comment]
Ok, that's good.  What screen are you running on?

**Comment by Fanny42** [comment]
Hello Justin,
Currently, I use a screen 1920x1080 to do my tests, in HDMI. When the
problem occured, I was using VNC viewer and the screen was shut down.
Do you think it could have a link ?

2018-05-27 1:09 GMT+02:00 Justin Shaw <notifications@github.com>:

**Comment by wyojustin** [comment]
There seems to be a lot of issues with preview and HDMI.  I got a lot of links with this google search "raspberry pi camera preview hdmi"

**Comment by Fanny42** [comment]
Thanks, I didn't think this could be the problem, I will test it as soon as possible, and I will update this feed, I think this might help someone else.

**Comment by wyojustin** [comment]
Thank you Fanny42!

**Comment by Fanny42** [comment]
Hi!
You were right wyojustin. I was using VNC, and the preview is not visible on this.
For the resolution, I got an issue with the preview that was way too big in 1920x1080. I put it at 1366x768, and now it's fine.
I am now working on a button to print the pictures, but I think I will do it without any problem.
Thank you for your help !

**Comment by wyojustin** [comment]
Hey!!! Congratulations!  Let me know your printer setup and I'll duplicate it.  We have a wedding coming up.

Thank you!
J

**Comment by osbock** [comment]
Just a note. The preview mode dumps video right into the screen buffer. If
you are using Remote Desktop like vnc you may or may not get the images.
Depending on the current state of the driver and vnc support if same.  Also
there appears to be a problem with “KMS” mode of the open GL driver

**Comment by Fanny42** [comment]
@wyojustin I use python-cups
`sudo apt-get install python-cups`

Then, you need to know the name of the printer you want to use :

```
import cups
conn = cups.Connection()
printers = conn.getPrinters()

for printer in printers:
     print printer, printers[printer]["device-uri"]
```

Here is what you get for example :
```
GG-P3010 socket://192.168.1.225:9116
zebra-raw usb://Zebra%20Technologies/ZTC%20LP%202824%20Plus?serial=36J141701319
HP-P3010 hp:/net/HP_LaserJet_P3010_Series?zc=NPI188F5A
```

Let's imagine you want to use zebra-raw printer (yesterday, I tried home with my Canon MG 5750, and a .png file, it works !) :
```
import cups
conn = cups.Connection()

conn.printFile( "zebra-raw", '/home/dom/PythonPcl/test/test-printer/zebra/demo.zpl', 'zebra demo', {} )
```
[Credits for the procedure](http://domeu.blogspot.com/2015/02/imprimante-zebra-usb-zpl-cups-et-python.html). It took me a long time to find this way !!

I added a button like the "SendEmail" button that launch this function.

Next steps : 

- Find the variable to use as the 2nd parameter (I am still a noob, so it take me a long time to find it !). Currently, I only make this function work if I type the path manually... Not ideal !!
- Find a way to resize picture to fit paper

Maybe in the futur I will add a flash, or even replace the Pi Camera by a Reflex, but one step at a time !!

**Comment by wyojustin** [comment]
@Fanny42 , thanks for the cups info.  I just tried your recipe by pasting your code into "cupstest.py" with no printers attached and got the following error:

```
pi@raspberrypi:~/tmp$ python cupstest.py 
Traceback (most recent call last):
  File "cupstest.py", line 2, in <module>
    conn = cups.Connection()
RuntimeError: failed to connect to server
pi@raspberrypi:~/tmp$ 
```

**Comment by wyojustin** [comment]
adding cups from the these instructions:
https://www.howtogeek.com/169679/how-to-add-a-printer-to-your-raspberry-pi-or-other-linux-computer/

**Comment by wyojustin** [comment]
That worked... now shows 0 printers!  I'll keep posting here on progress.

**Comment by Fanny42** [comment]
You need to add your printer using cups first. You will find the how to on google.
I forgot to mention this part, as it was already done for me, sorry for that.

As far as I am concerned, I am disappointed : my printer is not part of the open printing list (http://www.openprinting.org/printers) so I cannot change the page size. 
This is not a real problem, my printer is not the printer I will use with the PhotoBooth. I will choose one from the list, and pray that this will work as I expect !
