### ISSUE TITLE
Directory Not found. Not Archiving

### ISSUE THREAD

**Issue by confusedatfirst** [wyolum/TouchSelfie#16]
I'm working on a photo booth right now following the Makezine tutorial. I can't seem to get past Authentication though. I am able to enter my google user name and app specific password, but nothing else. I can allow it access to my google account and I can get the authentication code with ease. But when I return to the terminal to type it in, I get a screen loaded with errors. Starting with:

Directory Not Found. Not Archiving
/usr/local/lib/python2.7/dist-packages/oau2client/_helpers.py:255: Userwarning: Cannot Access./credentials.dat: No such file or directory
warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

The worst part is that some of the errors pop up after the Authentication Code prompt, so it blocks off my ability to type in the code. I'd enter more of the error code but it seems to show somewhat different errors each time, so that seems like it wouldn't help that much to put it here. I'm convinced if I can get the .credentials.dat and get it to find the right directory, it'll work though.

I'd also like to mention that while I have luakit as my default browser, it always seems to open in Chromium. Still trying to figure out why that's happening

I saw a previous poster have a very similar problem, posted as a reply in another issue, but it never got answered.

**Comment by laurentalacoque** [comment]
Hi :)

- For the first error "Directory not found, not archiving", you should just change the archive directory using the "customize" button in the app

- "Cannot Access ./credentials.dat" is simply a warning, the script is still waiting for you to type the authentication code. Just paste the code after the error and validate with Enter. This should get you rolling.

- luakit is not necessary, chromium is just fine

**Comment by osbock** [comment]
What laurent said! closing the issue
