### ISSUE TITLE
No module named oauth2client.client

### ISSUE THREAD

**Issue by SilentDev1** [wyolum/TouchSelfie#20]
raceback (most recent call last):
  File "./photobooth_gui.py", line 15, in <module>
    import custom
  File "/home/pi/git/TouchSelfie/scripts/custom.py", line 1, in <module>
    import listalbums
  File "/home/pi/git/TouchSelfie/scripts/listalbums.py", line 3, in <module>
    from credentials import OAuth2Login
  File "/home/pi/git/TouchSelfie/scripts/credentials.py", line 10, in <module>
    from oauth2client.client import flow_from_clientsecrets
ImportError: No module named oauth2client.client

**Comment by osbock** [comment]
Try the setup described in the Make magazine article. You haven't installed the google api python libraries
https://developers.google.com/api-client-library/python/guide/aaa_oauth
https://makezine.com/projects/raspberry-pi-photo-booth/

**Comment by SilentDev1** [comment]
I have followed that link, installed all the required " 
sudo apt-get update
sudo apt-get install python-imaging
sudo apt-get install python-gdata
sudo apt-get install python-imaging-tk
sudo pip install --upgrade google-api-python-client
sudo apt-get install luakit
sudo update-alternatives --config x-www-browser
"
but still getting the same error

**Comment by powpow12** [comment]
yea ran into this today @SilentDev1 , you find a workaround

**Comment by bamhm182** [comment]
I got around this problem with the following command:

pip install --upgrade oauth2client

TouchSelfie opened after that.
