### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by dingduck1** [wyolum/TouchSelfie#24]
The virtual keyboard doesn't have a "Send" button but instead it's "cancel" in place of the send button if it's a ".au" email address.

![2019-03-12 21_58_19-Window](https://user-images.githubusercontent.com/48477903/54198410-27bdf880-4512-11e9-97b3-cf3bdb21ccd3.jpg)

**Comment by wyojustin** [comment]
Dingduck1,

Thanks so much for downloading and testing TouchSelfie!  I hope it works to capture your event.  As far as the keyboard goes, when a vailid emial address is entered, the cancel button changes to "send".

Justin

**Comment by dingduck1** [comment]
Thanks for the reply Justin and what a fantastic Photo Booth!! As per the picture i had attached with my error log, once we use .au (because i'm in Australia, most of the people attending the function will be using a .au email address) the cancel button doesn't change to "send". If it's just .com then it does. I think the validation doesn't allow anything past .com?

**Comment by wyojustin** [comment]
Right you are!  I've fixed it to allow more than just one dot.  Thanks for testing.  Please try again.

Justin

**Comment by wyojustin** [comment]
I've re-opened the issue until you  confirm.

Justin

**Comment by dingduck1** [comment]
Thanks Justin. Silly question from a noob here. How do i update the files?

**Comment by wyojustin** [comment]
Change the line 568 in mykb.py
from
__email_validator = re.compile(r'^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$')

to
__email_validator = re.compile(r'^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,}$')

### remove the final "3"
