### ISSUE TITLE
Print photos from smartphone?

### ISSUE THREAD

**Issue by fmarzocca** [wyolum/TouchSelfie#28]
Hi,

I am wondering if your nice project is also able to download photos from bluetooth-connected smartphone and print them.
Is it restricted to only print the selfie that it takes?

Thanks
Fabio

**Comment by wyojustin** [comment]
Thanks Fabio,

This is an interesting idea, but we have no plans to print from phone at the moment.  I'll let you know if we come back to this.

Justin

**Comment by osbock** [comment]
also, most of these photo printers will also print directly from a phone
via bluetooth

**Comment by fmarzocca** [comment]
I was thinking to the capability to dowload a picture from the phone and then send it to the internal printer. In this way we could setup a Kiosk to print photos from smartphone. Of course, a graphical program should run on a touchscreen to interact with the user.

**Comment by osbock** [comment]
you could do something like this;
https://www.instructables.com/id/Bluetooth-How-to-send-a-copy-of-your-photos-and-vi/
