### ISSUE TITLE
Displaying a Message During Printing

### ISSUE THREAD

**Issue by wearebeta** [wyolum/TouchSelfie#30]
It would be very helpful if after you have pressed Print you get a message that will be printed. Since nothing is displayed at the moment, it is pressed so often until a photo comes, which takes about 10-15 seconds and then often the same photos come out multiple times.

**Comment by wyojustin** [comment]
Haha!  Great idea. This just happened to me last night.   Sorry about your extra copies!

**Comment by wearebeta** [comment]
I would pay 50,- € for a solution via PP ;)

**Comment by wyojustin** [comment]
yay!!! my first bounty!  Thank you so much.  Here is what I did:
1. disabled button for 10 seconds after a print attempt
2. display print status (either success or failure)

Please pull and test the changes.  If they are satisfactory, my paypall address is wyojustin and I use gmail.com

Thank you @wearebeta !!!

**Comment by wearebeta** [comment]
THANKS! How can I test it? I don't see any changes in the code!?

**Comment by wyojustin** [comment]
On the pi issue these commands.  We are working on the python3 version of TouchSelfie which will become the main branch very soon.  You can checkout this version and test the code with these commands on the RaspberryPi:

$cd <your_path_to>/TouchSelfie
$ git checkout python3
$ git pull

**Comment by wyojustin** [comment]
Re-opening until @wearebeta tests succeed.

**Comment by wyojustin** [comment]
Re-opening until @wearebeta tests succeed.

**Comment by wearebeta** [comment]
Thanks! will give a quick response.
