### ISSUE TITLE
camera support

### ISSUE THREAD

**Issue by NigelGreenway** [wyolum/TouchSelfie#40]
Really interested in this project and will download at some point over the next few days!

I was wondering what support this had for cameras like use cameras and DSLR tethering?

**Comment by wyojustin** [comment]
Thank you for checking out our project.

This project only supports the Rasperry Pi cameras.  I just ordered the new pi cameras to test with.

Justin

**Comment by osbock** [comment]
I experimented with DSLR tethering API, but it's not possible to have the
preview mode. Not hard to drop in, but you won't be able to see yourself.
