### ISSUE TITLE
Quality configuration

### ISSUE THREAD

**Issue by amaanr** [wyolum/TouchSelfie#7]
Trying to figure out how to config quality on the photos being taken. I'm using the v2 camera module which has a 8MP but its only uploading 1366x768 px images (1MP).

What is the best way to maximize quality on the images?

**Comment by yeti9** [comment]
Hi,
I use the v2 camera as well and I had the same issue. In the boothcam.py file after line 109: camera = mycamera.PiCamera(), I added this line camera.resolution = (3280,2464). In line 113 change resize=(1366,768) for resize=None.
 Now the picture are taken at full resolution.

I hope it will help.

**Comment by wyojustin** [comment]
Fixed in latest version.
